version: "2"

services:
  database:
    environment:
      POSTGRES_DB: newstream 
      POSTGRES_USER: newstream
      POSTGRES_PASSWORD: newstream
    restart: always
    image: postgres:12
    expose:
      - "5432"
  app:
    environment:
      NEWSTREAM_RUN_MIGRATIONS: 1
      NEWSTREAM_DEBUG: 1
      DATABASE_NAME: newstream
      DATABASE_USER: newstream
      DATABASE_HOST: database
      DATABASE_PASSWORD: newstream
      DJANGO_SUPERUSER_EMAIL: newstream@test.local
      DJANGO_SUPERUSER_PASSWORD: newstream
    image: newstream:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - database:database
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
